ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "budget_flights" DECIMAL(10,2);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "budget_hotel" DECIMAL(10,2);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "budget_entertainment" DECIMAL(10,2);
ALTER TABLE "Trip" ADD COLUMN IF NOT EXISTS "budget_food" DECIMAL(10,2);
ALTER TABLE "ExpenseEstimate" ADD COLUMN IF NOT EXISTS "date" DATE;
